version: '3.7'
services:
  mysql:
    image: mysql:5
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE} || 'Tarpaulin'
      MYSQL_USER: ${MYSQL_USER} || 'user'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} || 'password'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 80:80
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  mysql-data:
    name: asgard-mysql-data
